import {Dimensions, StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  Container: {
    width: '48%',
    height: (Dimensions.get('window').height * 0.7) / 3.2,
    backgroundColor: 'white',
    borderRadius: 24,
  },
  CardContainer: {
    flex: 1,
    borderRadius: 24,
    padding: 8,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  InnerContainer: {
    flex: 1,
    position: 'absolute',
    width: '100%',
    height: '100%',
    borderRadius: 16,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: 'black',
  },
  ImageContainer: {
    flex: 5,
    padding: 1,
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    filter: 'blur(2px)',
  },
  Image: {
    flex: 1,
    resizeMode: 'cover',
    borderTopLeftRadius: 14,
    borderTopRightRadius: 14,
  },
  TitleContainer: {
    flex: 1,
    justifyContent: 'center',
    padding: 10,
    borderTopWidth: 2,
    borderStyle: 'dashed',
  },
  Text: {fontWeight: 'bold', color: 'Black', textAlign: 'center'},
  AlbumCardBackContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  AlbumCardBackItemContainer: {
    flex: 1.5,
    gap: 10,
    justifyContent: 'center',
    marginTop: 20,
    margin: 10,
    width: '90%',
  },
  AlbumCardBackButtonContainer: {
    flex: 1,
    width: '90%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: '5%',
  },
  AlbumCardBackButton: {width: '48%'},
  DeleteContainer: {
    flex: 1,
    borderRadius: 10,
    backgroundColor: 'red',
    justifyContent: 'center',
    margin: 10,
    padding: 10,
    borderWidth: 1,
  },
  DeleteText: {
    textAlign: 'center',
    fontWeight: '700',
    color: 'white',
    fontSize: 18,
  },
  AlbumEditContainer: {
    borderRadius: 10,
    height: '40%',
    width: '60%',
    backgroundColor: 'blue',
    justifyContent: 'center',
    alignSelf: 'center',
    padding: 10,
    borderWidth: 2,
  },
  AlbumEditText: {
    textAlign: 'center',
    fontWeight: '700',
    color: 'white',
    fontSize: 18,
  },
  PlaceholderInnerContainer: {
    flex: 1,
    borderRadius: 16,
    borderWidth: 2,
    margin: 8,
    borderStyle: 'dashed',
    borderColor: 'black',
    backgroundColor: '#ABABAB80',
    justifyContent: 'center',
    alignItems: 'center',
  },
  PlaceholderItemButton: {
    width: '50%',
    height: '50%',
    borderRadius: 16,
    borderWidth: 2,
    borderStyle: 'dashed',
    justifyContent: 'center',
  },
  PlaceholderItemButtonText: {
    textAlign: 'center',
    fontWeight: '400',
    fontSize: 24,
  },
  CardFront: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    backfaceVisibility: 'hidden',
  },
  CardBack: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    backfaceVisibility: 'hidden',
  },
  ActiveCard: {
    zIndex: 1,
  },
  InactiveCard: {
    zIndex: 0,
  },
});
