import {Dimensions, StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  Container: {
    flex: 1,
    justifyContent: 'center',
    alignContent: 'center',
  },
  GlassContainer: {
    flex: 1,
    padding: 10,
    maxHeight: Dimensions.get('window').height * 0.5,
    width: Dimensions.get('window').width * 0.9,
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'center',
    backgroundColor: '#EDEDED70',
    verticalAlign: 'middle',
    marginBottom: Dimensions.get('window').height * 0.1,
  },
  AlbumContainer: {
    flex: 1,
    paddingTop: '5%',
    justifyContent: 'space-between',
    alignContent: 'center',
    gap: 20,
  },
  ButtonRowContainer: {
    height: Dimensions.get('window').height * 0.1,
    maxHeight: Dimensions.get('window').height * 0.5,
    width: Dimensions.get('window').width * 0.9,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignContent: 'center',
    alignItems: 'center',
  },
  Flatlist: {
    width: '100%',
    alignContent: 'center',
  },
  FlatlistColumnWrapperStyle: {
    justifyContent: 'space-between',
  },
  FlatlistContentContainerStyle: {
    gap: 20,
  },
  FlatlistItemContainer: {
    overflow: 'hidden',
    position: 'relative',
  },
  FlatlistItemNameContainer: {
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignContent: 'center',
    flex: 1,
    bottom: 0,
    position: 'absolute',
    width: '100%',
    minHeight: '20%',
    maxHeight: '20%',
  },
  FlatlistItemNameText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '500',
    marginLeft: 20,
    textAlignVertical: 'center',
  },
  FlatlistItemFavoriteButtonContainer: {
    position: 'relative',
    zIndex: 1,
  },
  FlatlistItemFavoriteButton: {
    flex: 1,
    fontSize: 24,
    color: 'red',
    position: 'absolute',
    top: 10,
    right: 10,
  },
  ImageComp: {
    width: Dimensions.get('window').width * 0.9 * 0.46,
    height: Dimensions.get('window').width * 0.9 * 0.46,
  },
  ImageButton: {
    flex: 1,
    flexDirection: 'row',
    height: '70%',
    maxWidth: '48%',
    maxHeight: 100,
    padding: 10,
    borderRadius: 10,
    backgroundColor: 'lightslategrey',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 1,
    borderWidth: 2,
    borderColor: 'darkslategrey',
  },
  ImageButtonText: {
    flex: 1,
    color: 'white',
    fontWeight: '700',
    fontSize: 18,
    textAlign: 'center',
    justifyContent: 'center',
    verticalAlign: 'middle',
  },
  ImageButtonIcon: {
    fontSize: 24,
    color: 'white',
  },
  NoImageText: {
    fontSize: 18,
    color: 'darkslategrey',
    fontWeight: '700',
  },
  NoAlbumIdContainer: {
    backgroundColor: 'white',
    borderRadius: 10,
    width: 300,
    borderWidth: 4,
    borderColor: 'darkslategrey',
    height: 200,
    justifyContent: 'center',
  },
  NoAlbumIdText: {
    padding: 20,
    textAlign: 'center',
    fontWeight: '700',
    fontSize: 24,
    color: 'darkslategrey',
    backgroundColor: 'white',
  },
});
