import {Dimensions, StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  Container: {
    flex: 1,
    justifyContent: 'center',
    alignContent: 'center',
  },
  GlassContainer: {
    flex: 1,
    padding: 10,
    maxHeight: Dimensions.get('window').height * 0.5,
    width: Dimensions.get('window').width * 0.9,
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'center',
    backgroundColor: '#EDEDED70',
    verticalAlign: 'middle',
    marginBottom: Dimensions.get('window').height * 0.1,
  },
  AlbumContainer: {
    flex: 1,
    paddingTop: '5%',
    justifyContent: 'space-between',
    alignContent: 'center',
    gap: 20,
  },
  ButtonRowContainer: {
    height: Dimensions.get('window').height * 0.1,
    maxHeight: Dimensions.get('window').height * 0.5,
    width: Dimensions.get('window').width * 0.9,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignContent: 'center',
    alignItems: 'center',
  },
  Flatlist: {
    width: '100%',
    alignContent: 'center',
  },
  FlatlistColumnWrapperStyle: {
    justifyContent: 'space-between',
  },
  FlatlistContentContainerStyle: {
    gap: 20,
  },
  FlatlistItemContainer: {
    overflow: 'hidden',
    position: 'relative',
  },
  FlatlistItemNameContainer: {
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignContent: 'center',
    flex: 1,
    bottom: 0,
    position: 'absolute',
    width: '100%',
    minHeight: '20%',
    maxHeight: '20%',
  },
  FlatlistItemNameText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '500',
    marginLeft: 20,
    textAlignVertical: 'center',
  },
  FlatlistItemButtonContainer: {
    flex: 1,
    flexDirection: 'row',
    position: 'absolute',
    right: 5,
    top: 5,
    justifyContent: 'flex-start',
    alignItems: 'center',
    minWidth: '70%',
    minHeight: '25%',
    maxWidth: '70%',
    maxHeight: '25%',
    gap: '25%',
    zIndex: 1,
  },
  FlatlistItemButton: {
    flex: 1,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: '100%',
    maxWidth: '35%',
    minWidth: '35%',
    borderRadius: '50%',
    zIndex: 1,
  },
  FlatlistItemFavoriteButton: {
    fontSize: 24,
    color: 'red',
  },
  FlatlistItemShareButton: {
    fontSize: 24,
    color: 'black',
  },
  ImageComp: {
    width: Dimensions.get('window').width * 0.9 * 0.46,
    height: Dimensions.get('window').width * 0.9 * 0.46,
  },
  ImageButton: {
    flex: 1,
    flexDirection: 'row',
    height: '70%',
    maxWidth: '48%',
    maxHeight: 100,
    padding: 10,
    borderRadius: 10,
    backgroundColor: 'lightslategrey',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 1,
    borderWidth: 2,
    borderColor: 'darkslategrey',
  },
  ImageButtonText: {
    flex: 1,
    color: 'white',
    fontWeight: '700',
    fontSize: 18,
    textAlign: 'center',
    justifyContent: 'center',
    verticalAlign: 'middle',
  },
  ImageButtonIcon: {
    fontSize: 24,
    color: 'white',
  },
  NoImageText: {
    fontSize: 18,
    color: 'darkslategrey',
    fontWeight: '700',
  },
  NoAlbumIdContainer: {
    flex: 1,
    padding: 10,
    maxHeight: Dimensions.get('window').height * 0.7,
    width: Dimensions.get('window').width * 0.9,
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'center',
    backgroundColor: '#EDEDED70',
    verticalAlign: 'middle',
  },
  NoAlbumIdContent: {
    flex: 1,
    justifyContent: 'center',
    width: '100%',
    gap: '5%',
  },
  NoAlbumIdText: {
    flex: 3,
    padding: 20,
    textAlign: 'center',
    fontWeight: '700',
    fontSize: 24,
    color: 'darkslategrey',
  },
  NoAlbumButton: {
    maxHeight: 120,
    minHeight: '60',
    width: '100%',
    borderRadius: 16,
    justifyContent: 'center',
    verticalAlign: 'middle',
    alignSelf: 'center',
    padding: 8,
    backgroundColor: 'darkslategrey',
    elevation: 2,
  },
  NoAlbumButtonDisabled: {
    maxHeight: 120,
    minHeight: '60',
    width: '100%',
    borderRadius: 16,
    justifyContent: 'center',
    verticalAlign: 'middle',
    alignSelf: 'center',
    padding: 8,
    backgroundColor: 'grey',
    elevation: 2,
  },
  NoAlbumButtonText: {
    textAlign: 'center',
    textAlignVertical: 'center',
    color: 'white',
    fontWeight: '700',
    fontSize: 18,
  },
  NoAlbumButtonErrorContainer: {
    width: '100%',
    backgroundColor: '#EE4E4E',
    justifyContent: 'center',
    padding: 15,
    borderRadius: 10,
  },
  NoAlbumButtonErrorText: {
    textAlignVertical: 'center',
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
  },
});
