import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  Container: {
    padding: 10,
    zIndex: 1,
    justifyContent: 'center',
  },
  GlassBackground: {
    flex: 1,
    alignSelf: 'center',
    justifyContent: 'center',
    height: '100%',
    width: '100%',
    position: 'absolute',
    backgroundColor: '#EDEDED',
    opacity: 0.7,
    filter: 'blur(4)',
    elevation: 1,
    zIndex: 0,
  },
  RegisterFormContainer: {
    flex: 6,
    justifyContent: 'space-evenly',
    alignContent: 'center',
  },
  TextInputContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    borderWidth: 1,
  },
  InputComp: {
    flex: 1,
    backgroundColor: 'white',
  },
  Label: {
    position: 'absolute',
    left: 18,
    top: -10,
    backgroundColor: 'white',
    paddingHorizontal: 20,
    zIndex: 1,
    shadowColor: 'white',
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderTopWidth: 1,
  },
  PromptIcon: {
    fontSize: 24,
    padding: 18,
  },
  PasswordHideIcon: {
    position: 'absolute',
    alignSelf: 'flex-end',
    bottom: 16,
    right: 20,
    fontSize: 18,
  },
  SubmitButton: {
    padding: 10,
    width: '100%',
    alignSelf: 'center',
    justifyContent: 'center',
    borderStyle: 'solid',
    borderWidth: 2,
    backgroundColor: 'white',
  },
  ButtonText: {alignSelf: 'center', fontWeight: 600, fontSize: 22},
  FailedMessageContainer: {
    flex: 1,
    padding: 10,
    opacity: 0.8,
    justifyContent: 'center',
    textAlign: 'center',
    alignItems: 'center',
    backgroundColor: '#EE4E4E',
  },
  MessageText:{
    fontWeight: 700,
  },
  Seperator: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  SeperatorLine: {
    height: 2,
    flex: 4,
    backgroundColor: 'black',
  },
  SeperatorText: {
    flex: 1,
    textAlign: 'center',
    justifyContent: 'center',
    fontWeight: 700,
    fontSize: 18,
  },
  OptionalRegisterButtonContainer: {
    flex: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  OptionalRegisterButton: {
    width: '45%',
    padding: 10,
    backgroundColor: 'white',
    borderWidth: 2,
    justifyContent: 'center',
  },
  OptionalRegisterButtonText: {
    fontWeight: 500,
    fontSize: 24,
    color: 'black',
    textAlign: 'center',
  },
  NavigateRegisterContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  NavigateRegisterText: {
    fontWeight: 500,
  },
  NavigateRegisterButton: {fontWeight: 700, color: '#0047AB'},
});
